package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * GnDocumentoAnexo generated by hbm2java
 */
@Entity
@Table(name = "td_asignacion_expediente")
public class TdAsignacionExpediente implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 3281088578592235383L;

	@Id
	@Column(name = "documento_anexo_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer asignacionExpedienteId;
	
	@Column(name="expediente_id")
	private Integer expedienteId;
	
	@Column(name="unidad_id")
	private Integer unidadId;
	
	@Column(name="resolutor_id")
	private Integer resolutorId;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private int usuarioId;

	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro")
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;
	
	@Column(name="estado_expediente")
	private Integer estadoExpediente;
	
	@Column(name="situacion_expediente")
	private Integer situacionExpediente;

	public Integer getAsignacionExpedienteId() {
		return asignacionExpedienteId;
	}

	public Integer getExpedienteId() {
		return expedienteId;
	}

	public Integer getUnidadId() {
		return unidadId;
	}
	
	public Integer getResolutorId() {
		return resolutorId;
	}

	public int getUsuarioId() {
		return usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}
	
	public Integer getEstadoExpediente() {
		return estadoExpediente;
	}
	
	public Integer getSituacionExpediente() {
		return situacionExpediente;
	}

	public void setAsignacionExpedienteId(Integer asignacionExpedienteId) {
		this.asignacionExpedienteId = asignacionExpedienteId;
	}

	public void setExpedienteId(Integer expedienteId) {
		this.expedienteId = expedienteId;
	}

	public void setUnidadId(Integer unidadId) {
		this.unidadId = unidadId;
	}
	
	public void setResolutorId(Integer resolutorId) {
		this.resolutorId = resolutorId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}
	
	public void setEstadoExpediente(Integer estadoExpediente) {
		this.estadoExpediente = estadoExpediente;
	}
	
	public void setSituacionExpediente(Integer situacionExpediente) {
		this.situacionExpediente = situacionExpediente;
	}
}
