package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * TdSituacionExpediente generated by hbm2java
 */
@Entity
@Table(name = "td_resolucion")
public class TdResolucion implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7548940248060493653L;

	@Id
	@Column(name = "resolucion_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer resolucionId;

	@Column(name = "nro_resolucion")
	private String nroResolucion;

	@Column(name = "expediente_id")
	private Integer expedienteId;

	@Column(name = "tipo_resolucion_id")
	private Integer tipoResolucionId;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_emision", nullable = false)
	@NotNull
	private Date fechaEmision;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_notificacion", nullable = true)	
	private Date fechaNotificacion;
	
	@Column(name="flag_proyecto_resolucion")
	private Boolean flagProyectoResolucion = Boolean.TRUE;
	
	@Column(name="unidad_id", nullable = false)
	private Integer unidadId;
	
	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private int usuarioId;

	public Integer getUnidadId() {
		return unidadId;
	}

	public void setUnidadId(Integer unidadId) {
		this.unidadId = unidadId;
	}

	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false)
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;

	public Integer getResolucionId() {
		return resolucionId;
	}

	public void setResolucionId(Integer resolucionId) {
		this.resolucionId = resolucionId;
	}

	public int getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

	public String getNroResolucion() {
		return nroResolucion;
	}

	public void setNroResolucion(String nroResolucion) {
		this.nroResolucion = nroResolucion;
	}

	public Integer getExpedienteId() {
		return expedienteId;
	}

	public void setExpedienteId(Integer expedienteId) {
		this.expedienteId = expedienteId;
	}

	public Integer getTipoResolucionId() {
		return tipoResolucionId;
	}

	public void setTipoResolucionId(Integer tipoResolucionId) {
		this.tipoResolucionId = tipoResolucionId;
	}

	public Boolean getFlagProyectoResolucion() {
		return flagProyectoResolucion;
	}

	public void setFlagProyectoResolucion(Boolean flagProyectoResolucion) {
		this.flagProyectoResolucion = flagProyectoResolucion;
	}

	public Date getFechaEmision() {
		return fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public Date getFechaNotificacion() {
		return fechaNotificacion;
	}

	public void setFechaNotificacion(Date fechaNotificacion) {
		this.fechaNotificacion = fechaNotificacion;
	}

}
