package com.sat.sisat.persistence.entity;
// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TdExpedienteDocumentoAnexoId generated by hbm2java
 */
@Embeddable
public class TdExpedienteDocumentoAnexoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -573885306956459943L;
	private int documentoAnexoId;
	private int expedienteId;

	public TdExpedienteDocumentoAnexoId() {
	}

	public TdExpedienteDocumentoAnexoId(int documentoAnexoId, int expedienteId) {
		this.documentoAnexoId = documentoAnexoId;
		this.expedienteId = expedienteId;
	}

	@Column(name = "documento_anexo_id", nullable = false)
	public int getDocumentoAnexoId() {
		return this.documentoAnexoId;
	}

	public void setDocumentoAnexoId(int documentoAnexoId) {
		this.documentoAnexoId = documentoAnexoId;
	}

	@Column(name = "expediente_id", nullable = false)
	public int getExpedienteId() {
		return this.expedienteId;
	}

	public void setExpedienteId(int expedienteId) {
		this.expedienteId = expedienteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TdExpedienteDocumentoAnexoId))
			return false;
		TdExpedienteDocumentoAnexoId castOther = (TdExpedienteDocumentoAnexoId) other;

		return (this.getDocumentoAnexoId() == castOther.getDocumentoAnexoId())
				&& (this.getExpedienteId() == castOther.getExpedienteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDocumentoAnexoId();
		result = 37 * result + this.getExpedienteId();
		return result;
	}

}
