package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * GnDocumentoAnexo generated by hbm2java
 */
@Entity
@Table(name = "td_documento_anexo")
public class TdDocumentoAnexo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 700112709432398787L;

	@Id
	@Column(name = "documento_anexo_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer documentoAnexoId;

	@Column(name = "nro_documento", nullable = true)
	private String nroDocumento;

	@Column(name = "tipo_documento_id", nullable = false)
	private Integer tipoDocumentoId;

	@Column(name = "nro_folio", nullable = false)
	private Integer nroFolio;

	@Column(name = "fecha_documento", nullable = false)
	private Date fechaDocumento;

	@Column(name = "content_id", nullable = true)
	private Integer contentId;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private int usuarioId;

	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro")
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;	
	
	@Column(name="unidad_id")
	private Integer unidadId;
	
	@Transient
	private boolean enEdicion = true;
	
	@Transient
	private boolean pendienteGuardado = false;

	@Transient
	private String unidadAsString;	

	@Transient
	private String usuarioAsString;
	
	
	public Integer getDocumentoAnexoId() {
		return documentoAnexoId;
	}

	public void setDocumentoAnexoId(Integer documentoAnexoId) {
		this.documentoAnexoId = documentoAnexoId;
	}

	public String getNroDocumento() {
		return nroDocumento;
	}

	public void setNroDocumento(String nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	public Integer getTipoDocumentoId() {
		return tipoDocumentoId;
	}

	public void setTipoDocumentoId(Integer tipoDocumentoId) {
		this.tipoDocumentoId = tipoDocumentoId;
	}

	public Integer getNroFolio() {
		return nroFolio;
	}

	public void setNroFolio(Integer nroFolio) {
		this.nroFolio = nroFolio;
	}

	public Date getFechaDocumento() {
		return fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}

	public Integer getContentId() {
		return contentId;
	}

	public void setContentId(Integer contentId) {
		this.contentId = contentId;
	}

	public int getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

	public boolean isEnEdicion() {
		return enEdicion;
	}

	public void setEnEdicion(boolean enEdicion) {
		this.enEdicion = enEdicion;
	}

	public boolean isPendienteGuardado() {
		return pendienteGuardado;
	}

	public void setPendienteGuardado(boolean pendienteGuardado) {
		this.pendienteGuardado = pendienteGuardado;
	}

	public String getUnidadAsString() {
		return unidadAsString;
	}

	public void setUnidadAsString(String unidadAsString) {
		this.unidadAsString = unidadAsString;
	}

	public String getUsuarioAsString() {
		return usuarioAsString;
	}

	public void setUsuarioAsString(String usuarioAsString) {
		this.usuarioAsString = usuarioAsString;
	}

	public Integer getUnidadId() {
		return unidadId;
	}

	public void setUnidadId(Integer unidadId) {
		this.unidadId = unidadId;
	}
}
