package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * TdExpedienteDocumentoAnexo generated by hbm2java
 */
@Entity
@Table(name = "td_expediente_documento_anexo")
public class TdExpedienteDocumentoAnexo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5524243171971347111L;

	@Id
	@Column(name = "expediente_documento_anexo_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer expedienteDocumentoAnexoId;

	@Column(name = "expediente_id")
	private Integer expedienteId;

	@Column(name = "documento_anexo_id")
	private Integer documentoAnexoId;

	@Column(name = "glosa")
	private String glosa;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_asignacion")
	private Date fechaAsignacion;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private int usuarioId;

	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro")
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;

	public Integer getExpedienteDocumentoAnexoId() {
		return expedienteDocumentoAnexoId;
	}

	public void setExpedienteDocumentoAnexoId(Integer expedienteDocumentoAnexoId) {
		this.expedienteDocumentoAnexoId = expedienteDocumentoAnexoId;
	}

	public Integer getExpedienteId() {
		return expedienteId;
	}

	public void setExpedienteId(Integer expedienteId) {
		this.expedienteId = expedienteId;
	}

	public Integer getDocumentoAnexoId() {
		return documentoAnexoId;
	}

	public void setDocumentoAnexoId(Integer documentoAnexoId) {
		this.documentoAnexoId = documentoAnexoId;
	}

	public String getGlosa() {
		return glosa;
	}

	public void setGlosa(String glosa) {
		this.glosa = glosa;
	}

	public Date getFechaAsignacion() {
		return fechaAsignacion;
	}

	public void setFechaAsignacion(Date fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}

	public int getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

}
