package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * TdSituacionExpediente generated by hbm2java
 */
@Entity
@Table(name = "td_resolutor")
public class TdResolutor implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8342622420160824253L;

	@Id
	@Column(name="resolutor_id")
	private Integer resolutorId;

	@Column(name = "unidad_id", nullable = true)
	private Integer unidadId;

	@Column(name = "usuario_resolutor_id", nullable = false)
	private Integer usuarioResolutorId;

	@Column(name = "fecha_inicio", nullable = false)
	private Date fechaInicio;

	@Column(name = "fecha_fin", nullable = false)
	private Date fechaFin;

	@Column(name = "rol", nullable = false)
	private String rol;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private int usuarioId;

	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false)
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;

	public Integer getResolutorId() {
		return resolutorId;
	}

	public Integer getUnidadId() {
		return unidadId;
	}

	public Integer getUsuarioResolutorId() {
		return usuarioResolutorId;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public String getRol() {
		return rol;
	}

	public int getUsuarioId() {
		return usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setResolutorId(Integer resolutorId) {
		this.resolutorId = resolutorId;
	}

	public void setUnidadId(Integer unidadId) {
		this.unidadId = unidadId;
	}

	public void setUsuarioResolutorId(Integer usuarioResolutorId) {
		this.usuarioResolutorId = usuarioResolutorId;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}
}
