package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * TdRequisito generated by hbm2java
 */
@Entity
@Table(name = "td_resultado")
public class TdResultado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5841366475262902582L;

	@Id
	@Column(name = "resultado_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int resultadoId;

	@Column(name = "expediente_id")
	private Integer expedienteId;

	@Column(name = "unidad_id")
	private Integer unidadId;

	@Column(name = "glosa")
	private String glosa;

	@Column(name = "fecha_atencion")
	private Date fechaAtencion;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private int usuarioId;

	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro")
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;

	public int getResultadoId() {
		return resultadoId;
	}

	public Integer getExpedienteId() {
		return expedienteId;
	}

	public Integer getUnidadId() {
		return unidadId;
	}

	public String getGlosa() {
		return glosa;
	}

	public Date getFechaAtencion() {
		return fechaAtencion;
	}

	public int getUsuarioId() {
		return usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setResultadoId(int resultadoId) {
		this.resultadoId = resultadoId;
	}

	public void setExpedienteId(Integer expedienteId) {
		this.expedienteId = expedienteId;
	}

	public void setUnidadId(Integer unidadId) {
		this.unidadId = unidadId;
	}

	public void setGlosa(String glosa) {
		this.glosa = glosa;
	}

	public void setFechaAtencion(Date fechaAtencion) {
		this.fechaAtencion = fechaAtencion;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

}
