package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * TdExpediente generated by hbm2java
 */
@Entity
@Table(name = "td_representante")
public class TdRepresentante implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4193320460217404125L;
	
	@Id
	@Column(name="representante_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer representanteId;
	
	@Column(name="apellidos_nombres")
	private String apellidosNombres;
	
	@Column(name="direccion")
	private String direccion;
	
	@Column(name="dni")
	private String dni;	

	@Column(name = "usuario_id")
	@NotNull
	private Integer usuarioId;
	
	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro")
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;
	
	@Column(name="cargo")
	private String cargo;
	
	//Nuevos campos
	@Column(name="primer_nombre")
	private String primerNombre;
	
	@Column(name="segundo_nombre")
	private String segundoNombre;

	@Column(name="ape_paterno")
	private String apePaterno;

	@Column(name="ape_materno")
	private String apeMaterno;

	@Column(name="razon_social")
	private String razonSocial;
	
	@Column(name="tipo_doc_identidad_id")
	private Integer tipoDocIdentidadId;
	
	@Column(name="tipo")
	private Integer tipo;
	
	public Integer getRepresentanteId() {
		return representanteId;
	}

	public void setRepresentanteId(Integer representanteId) {
		this.representanteId = representanteId;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public String getApellidosNombres() {
		return apellidosNombres;
	}

	public void setApellidosNombres(String apellidosNombres) {
		this.apellidosNombres = apellidosNombres;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}
	
	public String getCargo() {
		return cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}
	
	//nuevos campos agregados
	public String getPrimerNombre(){
		return primerNombre;
	}
	
	public void setPrimerNombre(String primerNombre){
		this.primerNombre = primerNombre;
	}
	
	public String getSegundoNombre(){
		return segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre){
		this.segundoNombre = segundoNombre; 
	}
	
	public String getApePaterno(){
		return apePaterno;
	}

	public void setApePaterno(String apePaterno){
		this.apePaterno = apePaterno;
	}
	
	public String getApeMaterno(){
		return apeMaterno;
	}

	public void setApeMaterno(String apeMaterno){
		this.apeMaterno = apeMaterno; 
	}
	
	public String getRazonSocial(){
		return razonSocial;
	}
	
	public void setRazonSocial(String razonSocial){
		this.razonSocial = razonSocial; 
	}
	
	public Integer getTipoDocIdentidadId(){
		return tipoDocIdentidadId;
	}
	
	public void setTipoDocIdentidadId(Integer tipoDocIdentidadId){
		this.tipoDocIdentidadId = tipoDocIdentidadId;
	}
	
	public Integer getTipo(){
		return tipo;
	}
	
	public void setTipo(Integer tipo){
		this.tipo = tipo;
	}
}
