package com.sat.sisat.persistence.entity;
// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * TdTipoTramite generated by hbm2java
 */
@Entity
@Table(name = "td_tipo_tramite")
public class TdTipoTramite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5242391289383629490L;
	private int tipoTramiteId;
	private String descCorta;
	private String descripcion;
	private int usuarioId;
	private char estado;
	private Date fechaRegistro;
	private String terminal;
	
	public TdTipoTramite() {
	}

	public TdTipoTramite(int tipoTramiteId, int usuarioId, char estado,
			Date fechaRegistro, String terminal) {
		this.tipoTramiteId = tipoTramiteId;
		this.usuarioId = usuarioId;
		this.estado = estado;
		this.fechaRegistro = fechaRegistro;
		this.terminal = terminal;
	}
	

	@Id
	@Column(name = "tipo_tramite_id", unique = true, nullable = false)
	public int getTipoTramiteId() {
		return this.tipoTramiteId;
	}

	public void setTipoTramiteId(int tipoTramiteId) {
		this.tipoTramiteId = tipoTramiteId;
	}

	@Column(name = "desc_corta", length = 50)
	@Size(max = 50)
	public String getDescCorta() {
		return this.descCorta;
	}

	public void setDescCorta(String descCorta) {
		this.descCorta = descCorta;
	}

	@Column(name = "descripcion", length = 200)
	@Size(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usuario_id", nullable = false)
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 23)
	@NotNull
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "terminal", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getTerminal() {
		return this.terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}
}
