package pe.gob.reniec.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-06-28T09:10:54.134-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ReniecConsultaDni", 
                  wsdlLocation = "https://ws5.pide.gob.pe/services/ReniecConsultaDni?wsdl",
                  targetNamespace = "http://ws.reniec.gob.pe/") 
public class ReniecConsultaDni extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.reniec.gob.pe/", "ReniecConsultaDni");
    public final static QName ReniecConsultaDniHttpsSoap11Endpoint = new QName("http://ws.reniec.gob.pe/", "ReniecConsultaDniHttpsSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("https://ws5.pide.gob.pe/services/ReniecConsultaDni?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReniecConsultaDni.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://ws5.pide.gob.pe/services/ReniecConsultaDni?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReniecConsultaDni(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReniecConsultaDni(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReniecConsultaDni() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReniecConsultaDni(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReniecConsultaDni(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReniecConsultaDni(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ReniecConsultaDniPortType
     */
    @WebEndpoint(name = "ReniecConsultaDniHttpsSoap11Endpoint")
    public ReniecConsultaDniPortType getReniecConsultaDniHttpsSoap11Endpoint() {
        return super.getPort(ReniecConsultaDniHttpsSoap11Endpoint, ReniecConsultaDniPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReniecConsultaDniPortType
     */
    @WebEndpoint(name = "ReniecConsultaDniHttpsSoap11Endpoint")
    public ReniecConsultaDniPortType getReniecConsultaDniHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(ReniecConsultaDniHttpsSoap11Endpoint, ReniecConsultaDniPortType.class, features);
    }

}
