package com.satc.pit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-09-18T16:04:51.989-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://pit.satc.com/", name = "RecordInfractorRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface RecordInfractorRemote {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaVehiculo", targetNamespace = "http://pit.satc.com/", className = "com.satc.pit.ConsultaVehiculo")
    @WebMethod
    @ResponseWrapper(localName = "consultaVehiculoResponse", targetNamespace = "http://pit.satc.com/", className = "com.satc.pit.ConsultaVehiculoResponse")
    public java.util.List<com.satc.pit.RecordVehiculo> consultaVehiculo(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        java.lang.String clave,
        @WebParam(name = "placaVehiculo", targetNamespace = "")
        java.lang.String placaVehiculo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaConductor", targetNamespace = "http://pit.satc.com/", className = "com.satc.pit.ConsultaConductor")
    @WebMethod
    @ResponseWrapper(localName = "consultaConductorResponse", targetNamespace = "http://pit.satc.com/", className = "com.satc.pit.ConsultaConductorResponse")
    public java.util.List<com.satc.pit.RecordConductor> consultaConductor(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        java.lang.String clave,
        @WebParam(name = "nroDniConductor", targetNamespace = "")
        java.lang.String nroDniConductor
    );
}
