package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * GnUnidad generated by hbm2java
 */
@Entity
@Table(name = "gn_unidad")
public class GnUnidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1858303671311648403L;

	@Id
	@Column(name = "unidad_id", nullable = false)
	private int unidadId;

	@Column(name = "unidad_padre_id", nullable = true)
	private Integer unidadPadreId;

	@Column(name = "descripcion")
	private String descripcion;

	@Column(name = "desc_corta")
	private String descCorta;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false)
	@NotNull
	private Date fechaRegistro;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private Integer usuarioId;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_actualizacion", nullable = true)
	private Date fechaActualizacion;

	public int getUnidadId() {
		return unidadId;
	}

	public void setUnidadId(int unidadId) {
		this.unidadId = unidadId;
	}

	

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDescCorta() {
		return descCorta;
	}

	public void setDescCorta(String descCorta) {
		this.descCorta = descCorta;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

	public Date getFechaActualizacion() {
		return fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUnidadPadreId() {
		return unidadPadreId;
	}

	public void setUnidadPadreId(Integer unidadPadreId) {
		this.unidadPadreId = unidadPadreId;
	}

}
