package pe.gob.sunarp.pide.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-07-02T11:17:50.541-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "PideService", 
                  wsdlLocation = "https://ws3.pide.gob.pe/services/SunarpPideService?wsdl",
                  targetNamespace = "http://controller.pide.sunarp.gob.pe/") 
public class PideService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controller.pide.sunarp.gob.pe/", "PideService");
    public final static QName PIDEWSServicePort = new QName("http://controller.pide.sunarp.gob.pe/", "PIDEWSServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://ws3.pide.gob.pe/services/SunarpPideService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PideService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://ws3.pide.gob.pe/services/SunarpPideService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PideService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PideService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PideService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PideService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PideService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PideService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PIDEWSService
     */
    @WebEndpoint(name = "PIDEWSServicePort")
    public PIDEWSService getPIDEWSServicePort() {
        return super.getPort(PIDEWSServicePort, PIDEWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PIDEWSService
     */
    @WebEndpoint(name = "PIDEWSServicePort")
    public PIDEWSService getPIDEWSServicePort(WebServiceFeature... features) {
        return super.getPort(PIDEWSServicePort, PIDEWSService.class, features);
    }

}
