package com.sat.sisat.persistence.entity;

// Generated 20/11/2012 10:29:09 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * TdRequisito generated by hbm2java
 */
@Entity
@Table(name = "td_data_valor")
public class TdDataValor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8599078676294020904L;

	@Id	
	@Column(name = "data_valor_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer dataValorId;

	@Column(name = "expediente_id", nullable = false)
	private Integer expedienteId;
	
	@Column(name = "tipo_valor_id", nullable = false)
	private Integer tipoValorId;

	@Column(name = "nro_valor", nullable = false)
	private String nroValor;

	@Column(name = "usuario_id", nullable = false)
	@NotNull
	private Integer usuarioId;
	
	@Column(name = "estado", nullable = false)
	@NotNull
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false)
	@NotNull
	private Date fechaRegistro;

	@Column(name = "terminal", nullable = false)
	@NotNull
	private String terminal;

	@Transient
	private boolean enEdicion = true;
	
	public Integer getDataValorId() {
		return dataValorId;
	}

	public void setDataValorId(Integer dataValorId) {
		this.dataValorId = dataValorId;
	}

	public Integer getTipoValorId() {
		return tipoValorId;
	}

	public void setTipoValorId(Integer tipoValorId) {
		this.tipoValorId = tipoValorId;
	}

	public String getNroValor() {
		return nroValor;
	}

	public void setNroValor(String nroValor) {
		this.nroValor = nroValor;
	}

	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

	public boolean isEnEdicion() {
		return enEdicion;
	}

	public void setEnEdicion(boolean enEdicion) {
		this.enEdicion = enEdicion;
	}

	public Integer getExpedienteId() {
		return expedienteId;
	}

	public void setExpedienteId(Integer expedienteId) {
		this.expedienteId = expedienteId;
	}

	
}
