package pe.gob.reniec.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-06-28T09:10:54.103-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://ws.reniec.gob.pe/", name = "ReniecConsultaDniPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ReniecConsultaDniPortType {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "consultar", output = "//ws.reniec.gob.pe/ConsultaPide/consultarResponse")
    @RequestWrapper(localName = "consultar", targetNamespace = "http://ws.reniec.gob.pe/", className = "pe.gob.reniec.ws.Consultar")
    @WebMethod(action = "consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://ws.reniec.gob.pe/", className = "pe.gob.reniec.ws.ConsultarResponse")
    public pe.gob.reniec.ws.ResultadoConsulta consultar(
        @WebParam(name = "arg0", targetNamespace = "")
        pe.gob.reniec.ws.PeticionConsulta arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "actualizarcredencial", output = "//ws.reniec.gob.pe/ConsultaPide/actualizarcredencialResponse")
    @RequestWrapper(localName = "actualizarcredencial", targetNamespace = "http://ws.reniec.gob.pe/", className = "pe.gob.reniec.ws.Actualizarcredencial")
    @WebMethod(action = "actualizarcredencial")
    @ResponseWrapper(localName = "actualizarcredencialResponse", targetNamespace = "http://ws.reniec.gob.pe/", className = "pe.gob.reniec.ws.ActualizarcredencialResponse")
    public pe.gob.reniec.ws.ResultadoActualizacionCredencial actualizarcredencial(
        @WebParam(name = "arg0", targetNamespace = "")
        pe.gob.reniec.ws.PeticionActualizarCredencial arg0
    );
}
